# DATASET & LOADER
#data_dir: '/home/lion/dataset/semantic_kitti/dataset/sequences/'

#root_dir: '/root/dataset/kitti/sequences/'
#checkpoints_path: "/root/dataset/kitti/checkpoints/"
#evaluation_path: "/root/dataset/kitti/evaluation/"

#uneven2
root_dir: '/root/dataset/uneven2/sequences/'
checkpoints_path: "/root/dataset/uneven2/checkpoints/"
evaluation_path: "/root/dataset/uneven2/evaluation/"

shift_cloud: true
lidar_height: 1.733
num_points: 100000  # max points in a pillar
grid_range: [-51.2, -51.2, 51.2, 51.2]
num_workers: 24

point_cloud_files: "pc_s_n"
labels_files: "lb_s_pl"


# VOXEL GENERATION 
# pc_range: [-49.4, -50, -4, 50.6, 50, 4] # cmcdot grid origin is at base_link not the velodyne so have to crop points from 0.6
pc_range: [-51.2, -51.2, -4, 51.2, 51.2, 4] # cmcdot grid origin is at base_link not the velodyne so have to shift cropping points
voxel_size : [0.8, 0.8, 8]
max_points_voxel : 64
max_voxels: 16384
input_features: 7

# VOXEL FEATURE EXTRACTOR 
vfe_filters: [64] # only one filter for now
with_distance: false

# MODEL PARAMETER
batch_size: 12 #设置输入模型的batch size
epochs: 25
use_norm: true  
num_gpus: 1
evaluate : false
save_checkpoints : true
base_lr: 0.003 #refer to mit paper

weight_decay: 0.0005
#momentum: 0.9
#clip: 0.25 # gradient clipping


# LOSS PARAMETER
alpha: 0.9 # per cell loss
beta: 0.1 # Smoothness loss


# RESULT DISPLAY
#model_name: "unet_kitti3"
print_freq: 20
physical_sampling: true


